# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FindSource(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FindSource()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFindSource(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FindSource
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FindSource
    def Memory(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # FindSource
    def Endpoint(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def FindSourceStart(builder): builder.StartObject(2)
def Start(builder):
    return FindSourceStart(builder)
def FindSourceAddMemory(builder, memory): builder.PrependUint64Slot(0, memory, 0)
def AddMemory(builder, memory):
    return FindSourceAddMemory(builder, memory)
def FindSourceAddEndpoint(builder, endpoint): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(endpoint), 0)
def AddEndpoint(builder, endpoint):
    return FindSourceAddEndpoint(builder, endpoint)
def FindSourceEnd(builder): return builder.EndObject()
def End(builder):
    return FindSourceEnd(builder)