# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

class Payload(object):
    NONE = 0
    Task = 1
    Pipeline = 2
    PipelineList = 3
    FindSource = 4
    JoinSource = 5
    SourceAlive = 6
    NodeAlive = 7
    NodeAccept = 8
    LinkLog = 9
