# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PipelineList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PipelineList()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPipelineList(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PipelineList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PipelineList
    def Items(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Pipeline import Pipeline
            obj = Pipeline()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PipelineList
    def ItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PipelineList
    def ItemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def PipelineListStart(builder): builder.StartObject(1)
def Start(builder):
    return PipelineListStart(builder)
def PipelineListAddItems(builder, items): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(items), 0)
def AddItems(builder, items):
    return PipelineListAddItems(builder, items)
def PipelineListStartItemsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartItemsVector(builder, numElems):
    return PipelineListStartItemsVector(builder, numElems)
def PipelineListEnd(builder): return builder.EndObject()
def End(builder):
    return PipelineListEnd(builder)