# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SourceAlive(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SourceAlive()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSourceAlive(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SourceAlive
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SourceAlive
    def Active(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # SourceAlive
    def Endpoint(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SourceAlive
    def PipelineUuid(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # SourceAlive
    def PipelineUuidAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # SourceAlive
    def PipelineUuidLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SourceAlive
    def PipelineUuidIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def SourceAliveStart(builder): builder.StartObject(3)
def Start(builder):
    return SourceAliveStart(builder)
def SourceAliveAddActive(builder, active): builder.PrependBoolSlot(0, active, 0)
def AddActive(builder, active):
    return SourceAliveAddActive(builder, active)
def SourceAliveAddEndpoint(builder, endpoint): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(endpoint), 0)
def AddEndpoint(builder, endpoint):
    return SourceAliveAddEndpoint(builder, endpoint)
def SourceAliveAddPipelineUuid(builder, pipelineUuid): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(pipelineUuid), 0)
def AddPipelineUuid(builder, pipelineUuid):
    return SourceAliveAddPipelineUuid(builder, pipelineUuid)
def SourceAliveStartPipelineUuidVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartPipelineUuidVector(builder, numElems):
    return SourceAliveStartPipelineUuidVector(builder, numElems)
def SourceAliveEnd(builder): return builder.EndObject()
def End(builder):
    return SourceAliveEnd(builder)